# Generated by Django 4.2.3 on 2023-10-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0002_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subquestion',
            name='subquestion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
