# Generated by Django 4.2.3 on 2023-11-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0005_alter_subquestion_subquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='subquestiontext',
            field=models.CharField(default='', max_length=200),
        ),
    ]
