# Generated by Django 4.2.3 on 2023-11-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0006_subquestion_subquestiontext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Category',
            new_name='category',
        ),
    ]
