# Generated by Django 4.2.3 on 2023-11-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0007_rename_category_question_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Doctor',
            new_name='doctor',
        ),
    ]
