# Generated by Django 4.2.3 on 2023-11-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0008_rename_doctor_question_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subquestion',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subquestion',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='subquestion',
            old_name='Question',
            new_name='question',
        ),
    ]
